### ISSUE TITLE
Switching log_level to DEBUG breaks printing :)

### ISSUE THREAD

**Issue by andrey-utkin** [FriedrichFroebel/brother_ql_web#22]
I'm with QL-600, setting the model to QL-500 (probably other models also work fine), with DEBUG in config it doesn't print while reporting success, it takes setting back to WARNING in config to make it print!

This happens with the last release on pypi and with git master.

**Comment by andrey-utkin** [comment]
FYI QL-580N model setting works well, this setting enables it to cut the printed output, while "QL-500" setting leaves it printed and uncut.

**Comment by FriedrichFroebel** [comment]
Thanks for your issue.

This is indeed the intended behavior, although probably undocumented: https://github.com/FriedrichFroebel/brother_ql_web/blob/e68f1592ab2c7b83ad9d4211f34efbd060d6490e/brother_ql_web/web.py#L196-L212 Debug mode is used to generate a local image file for further analysis (when doing changes, it is much easier to use this instead of having to connect my actual device each time), not for production.

For QL-600, QL-580N and other model handling, the `brother_ql` library is used - there should not really be any specific logic inside `brother_ql_ web`. I cannot test the different models in general, as I only own a QL-800 one.

**Comment by andrey-utkin** [comment]
I would agree if the setting was a general "mode", production vs debug. But this is `log_level`! It's super counter-intuitive that it changes behaviour!

**Comment by FriedrichFroebel** [comment]
That probably still is a matter of personal preference - running with debug log level should show debugging messages and allow debugging by this. Every other use does not really make sense for me. The default level is still `WARNING`.

What is your intended use case where you actually need to use the debug level output from a users perspective while indeed printing something?

**Comment by andrey-utkin** [comment]
> What is your intended use case where you actually need to use the debug level output from a users perspective while indeed printing something?

Learning in detail the new software I operate.
